import type { Metadata } from "next"
import Link from "next/link"
import { Geist, Geist_Mono } from "next/font/google"
import { SignedIn, SignedOut, UserButton } from "@clerk/nextjs"
import "./globals.css"
import { AppProviders } from "./providers"
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProviders>
          <div className="min-h-screen bg-background text-foreground">
            <header className="border-b bg-card/40">
              {/* 
                  Temporarily disabled react-grab scripts to diagnose browser issues 
                  as reported by user (right click disabled, crash).
              */}
              {/* {process.env.NODE_ENV === "development" && (
                <>
                  <Script
                    src="//unpkg.com/react-grab/dist/index.global.js"
                    strategy="beforeInteractive"
                  />
                  <Script
                    src="//unpkg.com/@react-grab/claude-code/dist/client.global.js"
                    strategy="lazyOnload"
                  />
                </>
              )} */}
              <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4 sm:px-8">
                <div className="flex items-baseline gap-2">
                  <Link
                    href="/"
                    className="text-sm font-semibold tracking-wide uppercase text-muted-foreground hover:text-foreground"
                  >
                    Makalah App
                  </Link>
                  <span className="hidden text-xs text-muted-foreground sm:inline-block">
                    AI-assisted papers
                  </span>
                </div>
                <nav className="flex items-center gap-4 text-sm">
                  <Link
                    href="/"
                    className="text-muted-foreground hover:text-foreground"
                  >
                    Home
                  </Link>
                  <Link
                    href="/pricing"
                    className="text-muted-foreground hover:text-foreground"
                  >
                    Pricing
                  </Link>
                  <Link
                    href="/about"
                    className="hidden text-muted-foreground hover:text-foreground sm:inline-block"
                  >
                    About
                  </Link>
                  <Link
                    href="/chat"
                    className="text-muted-foreground hover:text-foreground"
                  >
                    Chat
                  </Link>
                  <SignedIn>
                    <Link
                      href="/dashboard"
                      className="hidden text-muted-foreground hover:text-foreground sm:inline-block"
                    >
                      Dashboard
                    </Link>
                    <UserButton afterSignOutUrl="/" />
                  </SignedIn>
                  <SignedOut>
                    <Link
                      href="/sign-in"
                      className="text-muted-foreground hover:text-foreground"
                    >
                      Sign in
                    </Link>
                    <Link
                      href="/sign-up"
                      className="rounded-full border border-border px-3 py-1 text-xs font-medium text-foreground hover:bg-accent hover:text-accent-foreground"
                    >
                      Sign up
                    </Link>
                  </SignedOut>
                </nav>
              </div>
            </header>
            <main>{children}</main>
            <Toaster />
          </div>
        </AppProviders>
      </body>
    </html>
  )
}
