/**
 * Persistence layer type contracts for the harness runtime.
 *
 * These types mirror (but do not re-export) the Convex schema validators
 * defined in `convex/schema.ts` for the Phase 6 tables:
 *   - harnessRuns
 *   - harnessRunSteps
 *   - harnessEvents
 *
 * Research reference:
 *   `.references/agent-harness/research/2026-04-15-makalahapp-harness-v1-event-model-and-data-contracts.md`
 */
import type { Id } from "../../../../convex/_generated/dataModel"
import type { HarnessEventType } from "./event-types"

// ===================================================================
// Enums (mirrors Convex schema v.union literals)
// ===================================================================

export type RunStatus = "running" | "paused" | "completed" | "failed" | "aborted"

export type WorkflowStatus = "running" | "paused" | "failed" | "completed" | "aborted"

export type StepStatus = "running" | "completed" | "failed"

export type FailureClass =
  | "entry_failure"
  | "state_failure"
  | "tool_failure"
  | "verification_failure"
  | "guard_failure"
  | "unexpected_failure"

export type ApprovalMode = "default" | "required_for_high_impact"

export type PolicyBoundary = "read_only" | "bounded_mutation" | "blocked"

// ===================================================================
// Sub-object shapes embedded in table rows
// ===================================================================

export interface PolicyStateSnapshot {
  approvalMode: ApprovalMode
  currentBoundary: PolicyBoundary
  pendingApprovalDecisionId?: string
  lastPolicyReason?: string
  updatedAt: number
}

export interface ExecutorResultSummary {
  finishReason: string
  inputTokens?: number
  outputTokens?: number
  totalTokens?: number
}

/**
 * Flattened snapshot of `StepVerificationResult` for durable storage.
 * Drops `leakageDetails` body and `streamContentOverride` string content
 * to cap row size; replaces both with booleans suitable for replay.
 */
export interface StepVerificationSummary {
  canContinue: boolean
  mustPause: boolean
  pauseReason?: string
  canComplete: boolean
  completionBlockers: string[]
  leakageDetected: boolean
  artifactChainComplete: boolean
  planComplete: boolean
  streamContentOverridden: boolean
}

export interface ToolCallRecord {
  toolName: string
  toolCallId?: string
  resultStatus?: string
}

// ===================================================================
// Event envelope (research doc lines 128-142, 12 fields)
// ===================================================================

export interface HarnessEventEnvelope {
  eventId?: string                         // auto-generated by Convex mutation if omitted
  eventType: HarnessEventType              // canonical name; validated at adapter layer
  schemaVersion?: number                   // defaults to 1
  occurredAt?: number                      // ms epoch; defaults to Date.now() at mutation
  userId: Id<"users">
  sessionId: string
  chatId: Id<"conversations">
  runId?: Id<"harnessRuns">
  stepId?: Id<"harnessRunSteps">
  correlationId?: string
  causationEventId?: string
  payload: Record<string, unknown>
}

// ===================================================================
// Store interfaces (adapter layer over Convex mutations)
// ===================================================================

export interface CreateRunParams {
  conversationId: Id<"conversations">
  userId: Id<"users">
  paperSessionId?: Id<"paperSessions">
  workflowStage: string
  workflowStatus: WorkflowStatus
}

export interface UpdateRunStatusOptions {
  workflowStatus?: WorkflowStatus
  pausedAt?: number
  failureClass?: FailureClass
  failureReason?: string
}

export interface CompleteStepParams {
  status: Exclude<StepStatus, "running">
  executorResultSummary?: ExecutorResultSummary
  verificationSummary?: StepVerificationSummary
  toolCalls: ToolCallRecord[]
  completedAt: number
}

/**
 * Thin wrapper over the Convex `harnessRuns` / `harnessRunSteps` mutations.
 * No business logic — adapter composes related mutations where the logical
 * operation spans multiple DB calls (e.g., `startStep` = increment + create + setCurrent).
 */
export interface RunStore {
  createRun(
    params: CreateRunParams,
  ): Promise<{ runId: Id<"harnessRuns">; ownerToken: string }>

  linkPaperSession(
    runId: Id<"harnessRuns">,
    paperSessionId: Id<"paperSessions">,
  ): Promise<void>

  updateStatus(
    runId: Id<"harnessRuns">,
    status: RunStatus,
    opts?: UpdateRunStatusOptions,
  ): Promise<void>

  recordPolicyState(
    runId: Id<"harnessRuns">,
    policyState: PolicyStateSnapshot,
  ): Promise<void>

  /**
   * Composed operation: increments the run's `stepNumber`, creates the step
   * row with the new index, and sets `currentStepId` on the run.
   */
  startStep(
    runId: Id<"harnessRuns">,
  ): Promise<{ stepId: Id<"harnessRunSteps">; stepIndex: number }>

  completeStep(
    stepId: Id<"harnessRunSteps">,
    params: CompleteStepParams,
  ): Promise<void>

  completeRun(runId: Id<"harnessRuns">): Promise<void>
}

/**
 * Thin wrapper over the Convex `harnessEvents.emitEvent` mutation.
 * Assembles envelope defaults (schemaVersion, occurredAt) and validates
 * `eventType` against the canonical set.
 */
export interface EventStore {
  emit(envelope: HarnessEventEnvelope): Promise<{ eventId: string }>
}
